version: "3.9"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning #--requirepass 
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_ADDR=redis:6390
      - API_SERVER_ADDR=:8080
    ports:
      - "8080:8080"
    depends_on:
      - redis

